Added CoreDataService and comments
deffsin/WeatherApp pull request #11
Opened 2023-08-24 21:40 UTC by deffsin

2023-08-25 12:43 UTC, Hassanq911 requested changes

2023-08-25 12:43 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    let context = PersistenceController.shared.container.viewContext
Like network service can we make this service a bit more generic so that it can take any ns managed object and save, fetch or delete it?

2023-08-25 15:14 UTC, deffsin commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    let context = PersistenceController.shared.container.viewContext
Now i use generics there.

2023-08-28 10:13 UTC, Hassanq911 requested changes

2023-08-28 10:13 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    func fetchAllWeather<T: NSManagedObject>(_ objectType: T.Type) -> [T] {
Please rename the function. As these functions now can be used for any entity so name them accordingly like fetchAll, deleteAll ....

2023-08-28 10:13 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    func addWeather<T: NSManagedObject>(_ objectType: T.Type, with value: String, forKey key: String) {
Why are we passing parameters value and key ?

2023-08-28 10:13 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    func weatherExists<T: NSManagedObject>(_ objectType: T.Type, with value: String, forKey key: String) -> Bool {
Cant we just implement a function fetch here if it return nil then the data wont be present ?

2023-08-28 18:27 UTC, deffsin commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    func addWeather<T: NSManagedObject>(_ objectType: T.Type, with value: String, forKey key: String) {
So, the value i want to save - "value" and attribute key - "forKey"
For example let value = "Tallinn" and let forKey = "cityName"

2023-08-29 11:11 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    func addWeather<T: NSManagedObject>(_ objectType: T.Type, with value: String, forKey key: String) {
Well ideally there should be a way where we just store the whole object. If their already exist an object with the same primary id its attribute should be overritten. That way we dont have to specify columns when we are saving any data.

2023-08-29 11:21 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/CoreDataService.swift
> +    func weatherExists<T: NSManagedObject>(_ objectType: T.Type, with value: String, forKey key: String) -> Bool {
Hmmm i mean just adding query for fetching the particular object and if its not found then nil. The basis of the query would be the primary key

2023-08-29 12:02 UTC, Hassanq911 requested changes

2023-08-29 12:11 UTC, Hassanq911 approved these changes

2023-08-29 13:15 UTC, merged