Weather repository
deffsin/WeatherApp pull request #13
Opened 2023-09-05 13:56 UTC by deffsin

2023-09-07 08:11 UTC, Hassanq911 requested changes

2023-09-07 11:09 UTC, deffsin commented on WeatherApp/Services/CoreData/WeatherRepository.swift
> +            let weatherEntity = Weather(context: context)
What's the reason to use extension for that? Make code much cleaner and readable?

2023-09-08 08:40 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/WeatherRepository.swift
> +            let weatherEntity = Weather(context: context)
I would say redundancy so in future if we have lets say more entities we wont need to write out the mapping manually

2023-09-08 08:55 UTC, Hassanq911 requested changes

2023-09-08 08:55 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/WeatherRepository.swift
> +        if let existingWeather = coreDataService.find(Weather.self, with: weatherData.city, forKey: "city") {
```
let weatherEntity = coreDataService.find(Weather.self, with: weatherData.city, forKey: "city") ?? Weather(context: context)
weatherData.mapToWeatherEntity(weatherEntity)
```
maybe something like this to make it concise.

2023-09-11 08:46 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/WeatherRepository.swift
> +        let weatherEntity = coreDataService.find(Weather.self, with: weatherData.city, forKey: "city") ?? Weather(context: context)
Referring to my previous comment find a way that we don't have to explicitly write the attribute name for which we want to search the entity for rather just pass in the entity object in the coredata service's function and it does the rest. 
I was thinking for implementing a protocol for this purpose if their are no native solutions

2023-09-11 08:47 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/WeatherRepository.swift
> +            let weatherEntities = coreDataService.fetchAll(Weather.self)
This function can be a 1 liner 
`coreDataService.fetchAll(Weather.self).map { $0.toWeatherDto() }`

2023-09-11 08:48 UTC, Hassanq911 commented on WeatherApp/Services/CoreData/WeatherRepository.swift
> +            guard let weatherEntity = coreDataService.find(Weather.self, with: city, forKey: "city") else { return nil }
This function can be a 1 liner
`coreDataService.find(Weather.self, with: city, forKey: "city")?.toWeatherDto()`

2023-09-11 10:41 UTC, deffsin commented on WeatherApp/Services/CoreData/WeatherRepository.swift
> +        let weatherEntity = coreDataService.find(Weather.self, with: weatherData.city, forKey: "city") ?? Weather(context: context)
Well, i couldn't find another way besides using a protocol, so i'll try to using it

2023-09-18 11:19 UTC, Hassanq911 approved these changes

2023-12-21 11:08 UTC, closed without merging