Added Generic Network service
deffsin/WeatherApp pull request #9
Opened 2023-08-22 20:07 UTC by deffsin

2023-08-23 10:42 UTC, Hassanq911 requested changes

2023-08-23 10:42 UTC, Hassanq911 commented on WeatherApp/Services/Network/NetworkService.swift
> +enum NetworkError: Error {
@deffsin  I think we would need to handle unauthorised error (401) error as well
Also can you add like description for each error. So any where in the app that can be used to show message to the user later on ?

2023-08-24 09:52 UTC, Hassanq911 requested changes

2023-08-24 10:24 UTC, deffsin commented on WeatherApp/Services/Network/NetworkService.swift
> +    func makeAPICall<Model: Decodable>(urlRequest: URLRequest, completion: @escaping ((Result<Model, NetworkError>) -> Void)) {
I didn't saw this message.
Because i'm using the closure inside a function. This method will complete in the future, after the makeAPICall has alteady finished execution. And yeah, i havent added the Model, i've just implemented generic.

2023-08-24 10:28 UTC, Hassanq911 commented on WeatherApp/Services/Network/NetworkService.swift
> +    func makeAPICall<Model: Decodable>(urlRequest: URLRequest, completion: @escaping ((Result<Model, NetworkError>) -> Void)) {
So you understand the concept of @escaping. Its because the dataPublisher completion closure scope will out live the functions scope so if we want to call our closure in it we would also want our closure to be outside the scope of the function. So we write @escaping to indicate that the scope of this closure is escaping the scope of this function

2023-08-24 10:28 UTC, Hassanq911 approved these changes

2023-08-24 13:32 UTC, merged